export const TILE_SIZE = 64;
export const NUMBER_OF_BIOMES = 4;
export const TILES_PER_CHUNK = 8;
export const NUMBER_OF_CHUNKS = 16;
export const TOTAL_TILES =
    TILES_PER_CHUNK * TILES_PER_CHUNK * NUMBER_OF_CHUNKS * NUMBER_OF_CHUNKS;
export const CHUNK_SIZE = TILE_SIZE * TILES_PER_CHUNK;
