import type { PNG } from "pngjs";
import {
    MaxTileMaskWidth,
    masksEqual,
    type TileMask,
} from "../../src/game/map/tileMask.ts";
import { getPixelColor } from "../util/pngHelper.ts";
import type { PixelColor } from "../util/pixels.ts";

export const PondWaterColor: PixelColor = {
    red: 0,
    green: 108,
    blue: 255,
    alpha: 255,
};

export type PondMaskEntry = {
    file: string;
    mask: TileMask;
};

export type DuplicatePond = {
    file: string;
    duplicateOf: string;
};

export function readPondMask(png: PNG, file: string): TileMask {
    let minX = Number.MAX_SAFE_INTEGER;
    let minY = Number.MAX_SAFE_INTEGER;
    let maxX = -1;
    let maxY = -1;
    for (let y = 0; y < png.height; y++) {
        for (let x = 0; x < png.width; x++) {
            const color = getPixelColor(png, x, y);
            if (color.alpha === 0) {
                continue;
            }
            if (!isWaterColor(color)) {
                throw new Error(
                    `${file} has an unknown colour ${describeColor(color)} at ${x}/${y}, ponds may only contain water ${describeColor(PondWaterColor)} or transparent pixels`,
                );
            }
            minX = Math.min(minX, x);
            minY = Math.min(minY, y);
            maxX = Math.max(maxX, x);
            maxY = Math.max(maxY, y);
        }
    }

    if (maxX < 0) {
        throw new Error(`${file} has no water pixels`);
    }

    const width = maxX - minX + 1;
    const height = maxY - minY + 1;
    if (width > MaxTileMaskWidth) {
        throw new Error(
            `${file} is ${width} wide after trimming, ponds can be at most ${MaxTileMaskWidth} wide`,
        );
    }

    const rows: number[] = [];
    for (let y = minY; y <= maxY; y++) {
        let row = 0;
        for (let x = minX; x <= maxX; x++) {
            row = row << 1;
            if (getPixelColor(png, x, y).alpha !== 0) {
                row = row | 1;
            }
        }
        rows.push(row);
    }

    return { width, height, rows };
}

export function dedupeMasks(entries: readonly PondMaskEntry[]): {
    unique: PondMaskEntry[];
    duplicates: DuplicatePond[];
} {
    const unique: PondMaskEntry[] = [];
    const duplicates: DuplicatePond[] = [];
    for (const entry of entries) {
        const original = unique.find((kept) =>
            masksEqual(kept.mask, entry.mask),
        );
        if (original) {
            duplicates.push({ file: entry.file, duplicateOf: original.file });
        } else {
            unique.push(entry);
        }
    }
    return { unique, duplicates };
}

export function formatMaskSource(entry: PondMaskEntry): string {
    const rows = entry.mask.rows
        .map((row) => "0b" + row.toString(2).padStart(entry.mask.width, "0"))
        .join(", ");
    return `{ width: ${entry.mask.width}, height: ${entry.mask.height}, rows: [${rows}] }, // ${entry.file}`;
}

export function generatePondShapesSource(
    entries: readonly PondMaskEntry[],
): string {
    const lines = [
        "// Generated by pondpack from tileset/pond.<n>.png, do not edit.",
        "// Run `npm run pondpack` after changing the bitmaps.",
        'import type { TileMask } from "../src/game/map/tileMask.ts";',
        "",
        "export const pondShapes: readonly TileMask[] = [",
        ...entries.map((entry) => "    " + formatMaskSource(entry)),
        "];",
        "",
    ];
    return lines.join("\n");
}

function isWaterColor(color: PixelColor): boolean {
    return (
        color.red === PondWaterColor.red &&
        color.green === PondWaterColor.green &&
        color.blue === PondWaterColor.blue &&
        color.alpha === PondWaterColor.alpha
    );
}

function describeColor(color: PixelColor): string {
    return `rgba(${color.red}, ${color.green}, ${color.blue}, ${color.alpha})`;
}
