export const assets = {
    book_tab: "book_tab.png",
    bagOfGlitter: "bag_of_glitter.png",
    gemResource: "gem_resource.png",
    stoneResource: "stone_resource.png",
    woodResource: "wood_resource.png",
    book_grid_item: "book_grid_item.png",
    book_grid_item_focused: "book_grid_item_focused.png",
    book_right: "book_right.png",
    book_left: "book_left.png",
    farmSheet: "farm_field.png",
    cursor: "cursor.png",
    fancyWoodBackground: "fancy_wood_background.png",
    stoneSlateBackground: "stone_slate_background.png",
    stoneSlateBorder: "stone_slate_border.png",
    stoneSlateBorderSelected: "stone_slate_border_selected.png",
    stoneSlateButton: "stone_slate_button_2x.png",
    woodHouse: "house_sheet.png",
    tree: "tree_sheet.png",
    swordsman: "swordsman_sheet.png",
    farmer: "farmer_sheet.png",
    swipe_effect: "swipe_effect.png",
    coins: "coins.png",
    pixelanimals: "animals_sheet.png",
    goblinClub: "goblin_club_sheet.png",
    keep_sheet: "keep_sheet.png",
    stoneWoodWallsSheet: "stone_wood_walls.png",
    stoneWoodWallsHorizontal: "stone_wood_walls_horizontal.png",
    stoneWoodWallsVeritcal: "stone_wood_walls_vertical.png",
    stoneWoodWallsLeft: "stone_wood_walls_left.png",
    stoneWoodWallsRight: "stone_wood_walls_right.png",
    stoneWoodWallsUp: "stone_wood_walls_up.png",
    stoneWoodWallsDown: "stone_wood_walls_bottom.png",
    stoneWoodWallsBottomRight: "stone_wood_walls_br.png",
    stoneWoodWallsLeftBottom: "stone_wood_walls_lb.png",
    stoneWoodwallsLeftBottomRight: "stone_wood_walls_lbr.png",
    stoneWoodWallsLeftUp: "stone_wood_walls_lu.png",
    stoneWoodWallsLeftUpBottom: "stone_wood_walls_lub.png",
    stoneWoodWallsLeftUpRight: "stone_wood_walls_lur.png",
    stoneWoodWallsLeftUpRightBottom: "stone_wood_walls_lurb.png",
    stoneWoodWallsScaffold: "stone_wood_walls_scaffold.png",
    stoneWoodWallsUpBottomRight: "stone_wood_walls_ubr.png",
    stoneWoodWallsUpRight: "stone_wood_walls_ur.png",
};

export type ImageAsset = keyof typeof assets;
