name: CI
on:
  push:
    branches:
      - main
      
jobs:
  verify:
    name: Typecheck, check format and test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: npm i
      - run: npm run build:tsc
      - run: npm run check-format
      - run: npm run test